### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#12]
Sorry about this, but I am getting a little error! This is in R/scripts/IxPopDyMod.R. When I run `cfg <- read_config(config_path)` I get the error: `Error in read_csv(cfg$transitions, show_col_types = FALSE) : 
  unused argument (show_col_types = FALSE)`. Any idea? 

I can't test my `vary_param` right now because I can't get this cfg read it.

**Comment by mylesstokowski** [comment]
Aha! I actually had this error at one point. I believe updating the readr package will fix it because show_col_types is a new parameter for read_csv. 

I'll think about a better long-term fix for this... could be requiring a specific version of readr.

**Comment by dallenmidd** [comment]
That worked! Thanks. Great I will play around with all the config functions and also try out my `vary_param`
