### ISSUE TITLE
Constant host community

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#15]
If the user wants to have a constant host community, is there anyway we could make it saw the `host_den.csv` with just the density for each species and not have to repeat it for each day? Maybe if there is no `j_day` column the package woudl just assume constant host densities?

**Comment by mylesstokowski** [comment]
I think that'd be great - would definitely be cleaner and I don't see it being too hard to implement. I can try to take a stab at it in the next couple days. Since weather dependent transitions are implemented so similarly, do you think it's worth supporting constant weather too?

**Comment by dallenmidd** [comment]
Oh yeah it would be great to support it for weather too! Thanks for looking into this.

**Comment by mylesstokowski** [comment]
Just pushed some commits that should handle this. I also modified the host community csv for the ogden2005 config so it only has a row each for each host spp, and verified that we still get the same results.

**Comment by dallenmidd** [comment]
Great thanks! That was fast.
