### ISSUE TITLE
Remove code that makes assumptions about how life stages are named

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#20]
By convention, we've been encoding life stage names in three letter strings, where the characters encode age, infection status and the current process/activity (e.g. feeding, questing). 

The only place that we call `age()`, `process()` and `infected()` is [here](https://github.com/dallenmidd/IxPopDyMod/blob/63db055bd7e98ccdb80c82e3a261d6df879681a4/R/core_functions.R#L499-L501), in the function `run()`. This adds new columns to the model output data frame. These columns are then used in `graph_population_each_group()`, and just the `age` in `graph_population_overall_trend()`. So the proposed change is to remove all this, making the package flexible to arbitrary life stage naming.

**Comment by dallenmidd** [comment]
Oh yeah this seems reasonable to me. No reason to for the output to have `age_group`, `process` and `infected`. I think all it needs is `day`, `stage` and `pop`. So I think that we can remove it.
