### ISSUE TITLE
Trim dependencies

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#21]
- `igraph` is only used in `graph_lifecycle()`, which is not at all core functionality
- `parallel` is only used in `run_all_configs()`, which we could simply remove as this is just a thin wrapper around `run()`
- could use `data.frame`s instead of `tibble`s
- potentially, remove plotting functions and `ggplot2`

**Comment by mylesstokowski** [comment]
All sounds good to me. 
- I peeked through the package code and couldn't find any cases of `dplyr::` or `mutate(` or `filter(` in any code that I think we want to keep. So removing `dplyr` would be great - I think we can drop it as a dependency. While dropping it from the package itself, I think it's totally fine to use `dplyr` or other packages in the vignettes if convenient, and list it as a "suggests" optional dependency (just googled it and [this](https://stackoverflow.com/a/9900160) came up). But yes, I think rewriting `growth_rate` like that would be great
- Nice catch with `readr`. I think this and `tibble` go hand in hand. To me, the main benefit of having the `preds` in table format is nicer printing of a `config` object. Maybe worth seeing how it looks as a standard `data.frame`, and deciding based on that?

**Comment by dallenmidd** [comment]
Sounds good, I just made a new branch called `remove-ggplot-dplyr` where I will just get rid of the printing commands and re-write `growth_rate`.

**Comment by dallenmidd** [comment]
hm, I guess I am merging the PRs without a review. I must be hitting the wrong button. Anyway hopefully I didn't break anything. I merged my PR for updating the examples and readme. And then just merged this `remove-ggplot-dplyr` branch. I am not sure that `dplyr` is totally removed. I think I saw some `dplyr` commands in the `run` command.

**Comment by mylesstokowski** [comment]
Just looked over the two PRs - all looks good to me. But yeah, waiting for a review from each other could be helpful going forward. 

I believe there's some dplyr functionality remaining in the `core_functions.R`. I can remove that, and the non-core functionality in `config.R`, which will also allow removing the packages `igraph` and `yaml` and `parallel`. I'll also remove these from the `DESCRIPTION` file so they're not installed with `IxPopDyMod`.
