### ISSUE TITLE
Implement a shorter print for `life_cycle`

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#29]
A `life_cycle` is the longest component of a `config` when printed. It's a big, deeply nested hierarchical list of `transition`s. E.g. for `ogden2005`, it doesn't fit on one screen.

The proposed change would be to implement a `life_cycle.print` method that would print a much shorter representation. Alternatively, we might only want to print the shorter representation if printing an entire `config`, so we would just override the `config.print` method. 

A representation of a `life_cycle` might look something like this:

```
life_cycle with 22 transitions:
1. a -> b
2. b -> c
3. f -> a
... and 19 more transitions
```

**Comment by mylesstokowski** [comment]
As discussed, it would be helpful to include these numbered transitions

**Comment by dallenmidd** [comment]
I am not sure whether it would also be helpful to have a shorter print for `transition`. In my [new version of the readme](https://github.com/dallenmidd/IxPopDyMod/tree/dave-mod-examples#temperature-dependent-transitions), I call the transition either to show it is the correct one I want to modify a parameter for or to just talk about some function of the package. I wonder if we could also do a nice print here. I might be able to do that after seeing your `print.life_cycle` code.

**Comment by mylesstokowski** [comment]
I think that'd be great - feel free to go for it
