### ISSUE TITLE
Add a toggle for whether to use only first day of predictor day

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#30]
Each predictor in each `"duration"` type transition should be able to use either data from the initial day of the transition, or from the entire period of the transition. This excludes tick population as a predictor, since we don't know future tick population at each step. 

Currently, it is hard-coded so only the predictor `"host_density"` uses data from only the initial day of the transition, and others use the entire period of data.

The task: add a toggle so that users can choose which behavior they want. Currently, predictors in transitions are stored as a named vector, with names corresponding to the formal argument in the transition_function that they should be used for, and the values indicating where to get the predictor value (e.g. `temp`, `host_den`, or `larvae`). We need an additional piece of data for each - a boolean, with a name like `first_day_only`. 

So, the `predictors` attribute of a `transition` might be:
- a list (previously a character vector)
- name of each element corresponds to formal argument in transition_function, as before
- value of each element is a list like:
```R
list(pred = "host_den", first_day_only = TRUE) # should default to FALSE
```

**Comment by dallenmidd** [comment]
This one is tricky! It feels like the highest priority to me, but it can be hard to wrap your head around what is going on. Still I think that we do want to address this one.

**Comment by mylesstokowski** [comment]
Yep, agreed. From a workflow perspective, might be easier to get to this (new functionality) once we've handled some of the other improvement-type tasks

**Comment by dallenmidd** [comment]
This looks great! I did a code review, so you can feel free to merge the PR. The only question I had was, you re-did the code for ogden2005, do we need to redo the code for the other example configs?

**Comment by dallenmidd** [comment]
OHHH my bad, I see you have that in another PR. Great!
