### ISSUE TITLE
Reconsider naming of elements of a config

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#31]
There are some cases of attributes of a config that overlap with `IxPopDyMod::` functions. This could be confusing. E.g. `predictors()` is a function to create a table of predictor data, as well as a parameter to `transition()`.

**Comment by dallenmidd** [comment]
hmm, is `predictors` a function that a user will actually use? Or just an internal function? If it is an internal function, than it doesn't seem like that big a deal to me. That being said, if it is best practice (or something) to keep the names different, than I guess we could re-name the config elemetns.

**Comment by mylesstokowski** [comment]
Currently `predictors()` is an external function (it has the `#' @export` tag). I think this is certainly low priority - but if either of us thinks up more intuitive/distinct names, it could be a nice change for clarity.

**Comment by mylesstokowski** [comment]
Closing b/c this is very low priority
