### ISSUE TITLE
Remove unused things in repo

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#39]
A running list of things that could safely be removed from the repo. We could always get these back by looking in the git history. Note that we should also remove any of these from `.Rbuildignore`
- `outputs/` - this just has output csvs from model runs, which we can regenerate by running the model, and it's bad practice to have data tracked with git
- `benchmarking/` - this is just old experiments to try to speed up the code, but no longer relevant and wouldn't be much help for any future optimization efforts
- `scripts/` - four R scripts that I don't think we need
- `sources.csv` - this is very incomplete
- `data-raw/`: we don't want to remove this entirely, but there are dead parts e.g. `data-raw/config_ex_2/`

**Comment by mylesstokowski** [comment]
^ @dallenmidd fyi some ideas for repo cleanup, feel free to add any thoughts

**Comment by mylesstokowski** [comment]
@dallenmidd all sounds good to me. Agreed about vignettes - I think that'd be an ideal way to show reproducing Ogden. 

Perhaps it makes sense to split this into two tasks/PRs:
1. Removing all the old stuff, barring what we want to turn into vignettes
2. Turning `data-raw/ogden2005/` and potentially other model configs there into vignettes. Winter tick is probably another good candidate.

I'm happy to take a stab at either/both of these, and also happy to divvy it up.

**Comment by mylesstokowski** [comment]
Quick follow up to the above - I remember some difficulties with vignettes when preparing the package for CRAN. Just took a look at [this](https://r-pkgs.org/vignettes.html) resource which will likely come in handy.

**Comment by dallenmidd** [comment]
Sounds good to me about splitting into two PRs. If the vignette is too much work, I think maybe we could also just have a `.rmd` explainer or something in `data-raw/ogden2005/` but maybe that is not really best practice? I can remove the old stuff. And then myabe we can each take one of the vignettes. Do you want to do the winter tick and I will do ogden?

**Comment by mylesstokowski** [comment]
Perfect. Happy to take winter tick. Might be good to wait to create these new configs till [this](https://github.com/dallenmidd/IxPopDyMod/issues/30) is implemented - should have an update on it soon.

**Comment by dallenmidd** [comment]
Sounds good!
