### ISSUE TITLE
Update function documentation

### ISSUE THREAD

**Issue by mylesstokowski** [dallenmidd/IxPopDyMod#46]
Per discussion in #41 , a few functions have out-of-date function documentation that should be updated. Most of the changes needed are in the core functions that could still change a bit, so probably best to hold off on updating those docs. `to_short_string()` and `transition()` have docs that could be updated now.

**Comment by dallenmidd** [comment]
I can take care of these!

**Comment by dallenmidd** [comment]
@mylesstokowski I pushed the changes to my branch, but I am not sure how to rebuild the package so it updates the documentation. When I try `devtools::load_all()` and then `?transition` I get an error that files are missing. Could you tell me how to rebuild the package to update the doc files? Thanks!

**Comment by dallenmidd** [comment]
That works! I put in a PR so you can check the updated documentation and merge it in to the `master` branch.
