### ISSUE TITLE
More help to user for de-bugging

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#5]
The `test_transitions` function is great! I was wondering about an addition to it that preforms some checks. Maybe this additional `do_checks` or whatever would take place automatically in the `run` function. It could check each row of `tick_transitions` see what function is used, then see what parameters that function takes and see whether those parameters are included in `tick_parameters`. It coudl give an error message like "parameter __ is missing from function __ in the transition from __ to __". I don't know if the check could also some how check whether all life stages go somewhere and come from somewhere, if you no what I mean.

I guess I am thinking outloud here and I am sure these are things you ahve already considered. But just wanted to get it down, while I had it in my mind.

**Comment by mylesstokowski** [comment]
... a lot has changed since this was last active, but now the series of checks in `validate_config()` is accomplishing essentially what is described here, so I'm closing this issue.
