### ISSUE TITLE
Get paper ready for submission

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#55]
- [x] Finish the [Vignettes issue](https://github.com/dallenmidd/IxPopDyMod/issues/41) -- Dave and Myles
- [x] Push the new version of the package to CRAN -- Myles
- [x] Make sure Ogden appendix is ready for submission. This may mean making a slightly different version with citations in their style and some stuff added or removed to make it sound more like a paper and less like a readme. -- Dave ([here it is](https://drive.google.com/drive/folders/1ByaJapJgsxMJLEcMMEcK8i0-NKVelShv))
- [x] As above for the winter tick appendix -- Dave ([here it is](https://drive.google.com/open?id=1jwWbD-p7jTi9azkWh2W92X_qnfbLmSLV&usp=drive_fs))
- [x] Myles read of the current version of manuscript and any edits/comments -- Myles
- [x] Dave final read of manuscript -- Dave
- [x] Myles final read of manuscript -- Myles ([now in latex, you can find it here](https://drive.google.com/file/d/1bpbxZrIpyqUdLRYBF-egzak1i-FTJv1t))
- [x] Reformat manuscript for their submission guidelines -- Dave 
 
I think that we are close, so I just wanted to have some place to put down what I see as our to-do list. Feel free to add if you think of something else we need to do. Most of these can be my jobs. I think I just need your help with one final look over the package so you think it is ready to push the next version to CRAN. I assume we want that version up when we submit the manuscript. And then just another read of the manuscript now and then again right before submission. I am happy to do all the reformatting for the journal guidelines and also re-doing the appendices so they have the right tone for an academic paper versus github readme.

**Comment by mylesstokowski** [comment]
@dallenmidd thanks for writing this up, super helpful. The checklist looks right to me!

**Comment by mylesstokowski** [comment]
Updated version of the package is live on CRAN: https://cran.r-project.org/web/packages/IxPopDyMod/index.html

**Comment by dallenmidd** [comment]
Submitted!
