### ISSUE TITLE
Recreate Ogden Table 2/Fig 7

### ISSUE THREAD

**Issue by dallenmidd** [dallenmidd/IxPopDyMod#7]
So cool that you could recreate Ogden figure 4. I think another goal would be to download the climate normals for a range of sites. No need to do it for all of them in Table 2. But maybe pick like 6 or so from Ontario in Table 2. Then use the [Canada Climate Normals](https://climate.weather.gc.ca/climate_normals/index_e.html) website and get the monthly climate normals. From that we shoudl be able to roughly re-create Fig 7, just with six points. Make sure to pick sites across the full latitude/degree day range for Ontario.

**Comment by mylesstokowski** [comment]
We did this a while ago but didn't close this issue. I just polished up the code for this so that it uses the new `config` structure. Here's the output plot.

![image](https://user-images.githubusercontent.com/35432444/134813378-22c5c5ce-4990-43a7-bba3-7ef6ec361870.png)
